default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['BELLE_REALTY_DB_USERNAME'] %>
  password: <%= ENV['BELLE_REALTY_DB_PASSWORD'] %>

development:
  <<: *default
  database: <%= ENV['BELLE_REALTY_DB_DEVELOPMENT'] %>

test:
  <<: *default
  database: <%= ENV['BELLE_REALTY_DB_TEST'] %>

production:
  <<: *default
  username: <%= ENV['BELLE-REALTY_DATABASE_USERNAME'] %>
  password: <%= ENV['BELLE-REALTY_DATABASE_PASSWORD'] %>
  url: <%= ENV['DATABASE_URL'] %>
